name: "Hello World"
description: "Greet someone and record the times"
inputs:
  slicer:
    required: true
  alchemy_api_key:
    required: true
  GITHUB_TOKEN:
    required: true
  SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}

runs:
  using: "node16"
  main: "dist/src/index.js"
