name: "Hello World"
description: "Greet someone and record the time"
inputs:
  slicer:
    required: true
  alchemy_api_key:
    required: true
  GITHUB_TOKEN:
    required: true

runs:
  using: "node16"
  main: "dist/src/index.js"
